### ISSUE TITLE
Vagrantfile installation fails due to GitHub's token req't

### ISSUE THREAD

**Issue by bitwombat** [zendframework/ZendSkeletonApplication#299]
vagrant up shows this:

==> default: Use it: php composer.phar
==> default: Loading composer repositories with package information
==> default: Installing dependencies (including require-dev) from lock file
==> default:   - Installing zendframework/zend-db (2.5.1)
==> default:     Downloading
==> default:     **Failed to download zendframework/zend-db from dist: Could not authentica**
==> default:     Now trying to download from source

The error message line is truncated, but from running composer install manually, I can see it wants an OAuth token... easy enough to do but how to do this in an automated Vagrant installation?  Check for user's own ~/.composer/auth.json and copy it into the Vagrant machine (or install script)?

**Comment by jeremiahsmall** [comment]
One option would be to omit the composer install line from the provisioner and leave it up to the user to install. Another would be to use a more full featured vagrant recipe. Coincidentally, I posed these questions on the apigility skeleton yesterday. https://github.com/zfcampus/zf-apigility-skeleton/pull/106

**Comment by weierophinney** [comment]
This should only happen if you exceed the API rate limit for the given day from your IP address.

If you're running into it regularly — e.g., due to your CI server doing many installs over a given hour, etc. — you have two options:

- Create global git and/or composer configuration for the user running the command.
- Add configuration to the `composer.json` for the github oauth2 token; if you do this, make sure your composer.json is in a **private** repository!
  ```json
  {
    "config": {
      "github-oauth": {
        "github.com": ""
      }
    }
  }
```

I'm closing this, as the new Vagrant configuration no longer runs `composer install` by default, which puts the onus on the user to resolve such issues.
