### ISSUE TITLE
Installer .lock file error after initial install

### ISSUE THREAD

**Issue by jeremiahsmall** [zendframework/ZendSkeletonApplication#335]
The installer is pretty darn neat. I found a reproducible issue, but not sure how to suggest fixing it yet. Maybe @weierophinney will know.
# To reproduce
- clone the repo and checkout develop branch
- run `composer install`
- manually choose all the non-default answers to the installer prompts (e.g. non-minimal, and then accept every optional module)
- the install will complete, apparently with no errors. The console says `Complete!` and the app runs in the browser.
- run `composer install` again immediately (I was curious what installer prompts if any I would get)
# Actual result

Composer fails to run with this error

```
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

  [ErrorException]                       
  Illegal offset type in isset or empty  
```

If I then run `composer update`, it completes fine, but it does update many things in the lock file, and it also updates zend-servicemanager

```
  - Removing zendframework/zend-servicemanager (3.0.3)
  - Installing zendframework/zend-servicemanager (3.1.0)
```

See https://gist.github.com/jeremiahsmall/d5c54f283dddf2f4ba3e11d0cd39fa11#file-zendframework_skeleton_installer_output-txt-L173-L192
# Expected result

Not really sure, but at least no error.

**Comment by Ocramius** [comment]
@jeremiahsmall can you do a `composer update nothing` and see if the lock file is in sync afterwards?

**Comment by jeremiahsmall** [comment]
@Ocramius yes, you are right. If I run `composer update nothing` immediately after it completes, the .lock file does get fixed (if I stage the original .lock file first, it's clear that the .lock file has been totally regenerated), and after that running `composer install` doesn't throw any errors.

```
eyelab:ZendSkeletonApplication jeremiah$ composer update nothing

Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files

eyelab:ZendSkeletonApplication jeremiah$ composer install

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

```

**Comment by Ocramius** [comment]
So the only diff is probably the hash, given that `composer.json` is modified in some minor details...

**Comment by jeremiahsmall** [comment]
Well yeah, diffs are the hash, and corrected syntax. Something is wrong with the syntax of the original .lock file that gets created.

**Comment by weierophinney** [comment]
This may be due to the fact that the installer uses some composer internals to update the lock file (though everything I use is part of the public API, and I had some of their devs look it over for me).

I was able to reproduce, and, to check a bit more thoroughly, ran `composer install -vvv` so I could see full stack traces. The issues are within Composer itself; the exception occurs within `Composer\Package\Version\VersionParser`, as invoked by their installer; none of our own plugins are in play.

As such, I'd argue we should likely raise it with the composer team, though I suspect this may be a huge edge case. We can also potentially document it in an FAQ somewhere, if others stumble upon the problem.

With regards to having zend-servicemanager v3.0.3 vs v3.1.0, I have a number of other fixes to get in, and will try and do an updated `composer.lock` with the most recent versions as well.

**Comment by weierophinney** [comment]
Both 3.0.1 and 3.0.2 have updated lock files, and I am no longer able to reproduce.
