### ISSUE TITLE
configuration problem

### ISSUE THREAD

**Issue by armenio** [zendframework/ZendSkeletonApplication#357]
using last version of zf (3)

i have two problems:

1 - Factory configuration not working (no effect)
2 - Controller Invokable only works the way I'm putting here
```php
    'controllers' => [
        'factories' => [
            Controller\IndexController::class => Controller\IndexControllerFactory::class, <-------------------- 1
        ],
        'invokables' => [
            'index' => Controller\IndexController::class, <-------------------------------------- 2
        ],
    ],`

**Comment by alextech** [comment]
A bit challenging with this little info (plus dont want to turn issue tracker into public forum).

1. can be either due to 
1a mismatched router configuration, where route path has different controller name than key in factories. Easiest way to check is replace right of => with an anonymous function with simple and see if it runs.
Controller\IndexController:class => function (ContainerInterface $sm) {
 echo "I am running";
}
1b. IndexControllerFactory may not extend Zend\ServiceManager\Factory\FactoryInterface and if you have error display turned off you will not see messages about that.

2 
'factories' => [
Controller\IndexController::class => InvokableFactory::class
]

does not work?
Would again be similar to 1a.

**Comment by armenio** [comment]
I change my router from 
```php
'routes' => [
            'admin' => [
                'type' => Literal::class,
                'options' => [
                    'route' => '/admin',
                    'defaults' => [
                        'controller' => Controller\IndexController::class,
                        'action' => 'index',
                    ],
                ],
                'may_terminate' => true,
                'child_routes' => [
                    'controller' => [
                        'type' => Segment::class,
                        'options' => [
                            'route' => '/:controller',
                            'constraints' => [
                                'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                            ],
                            'defaults' => [
                                'action' => 'index',
                            ],
                        ],
                        'may_terminate' => true,
                        'child_routes' => [
                            'action' => [
                                'type' => Segment::class,
                                'options' => [
                                    'route' => '/:action',
                                    'constraints' => [
                                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                    ],
                                ],
                                'may_terminate' => true,
                                'child_routes' => [
                                    'wildcard' => [
                                        'type' => Wildcard::class,
                                    ],
                                    'id' => [
                                        'type' => Segment::class,
                                        'options' => [
                                            'route' => '[/:id]',
                                            'constraints' => [
                                                'id' => '[0-9]+',
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],`


to 

```php
'router' => [
        'routes' => [
            'admin' => [
                'type' => Segment::class,
                'options' => [
                    'route' => '/admin[/:controller[/:action[/:id]]]',
                    'constraints' => [
                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'id' => '[0-9]+',
                    ],
                    'defaults' => [
                        'controller' => Controller\IndexController::class,
                        'action' => 'index',
                        'id' => 0,
                    ],
                ],
                'may_terminate' => true,
                'child_routes' => [
                    'wildcard' => [
                        'type' => Wildcard::class,
                    ],
                ],
            ],
        ],
`

and now, the the controller factory are called.

**Comment by alextech** [comment]
Somewhat makes sense. Wonder if because optional slash [/] was not specified in original path parent so browser may have appended it. Good job finding it!

**Comment by huanyusun** [comment]
It doesn't work when do this commond "composer development-enable". The Apache return code 500

**Comment by generalroland** [comment]
@huanyusun:
open composer.json
edit:
"autoload": {
    "psr-4": {
        "Application\\": "module/Application/src/",
        "Application2\\": "module/Application2/src/"            //add this
    }
},

then run command:
$ composer dump-autoload
or:
composer dump-autoload (on windows)

**Comment by weierophinney** [comment]
The primary problem here is including `:controller` in your routing segments. Don't do this. Ever.

There are a few reasons not to do it:

- First, it then requires you to create aliases for your controllers, due to the fact that controller names are PHP class names, which include namespace segments, which include `\\` characters... which are encoded when provided on the URL. In most cases, you don't want that, so you must then alias a "short" controller name to a class name. This was done previously using `invokables`, which you can still do, but these internally then get configured to a combination of an alias and an `InvokableFactory` mapped to the class name. You might as well duplicate routes, as matching is faster, and there's fewer possibilities of problems with service names.
- Second, you may need a *bunch* of aliases, as users may try a ton of different cAsINg CoMBINaTioNs in the URI, and you now have to accommodate these in your service configuration to ensure they're all valid. (zend-servicemanager v3 is *case sensitive*.)
- Third, it's a performance and security issue. In the best case scenario, the requested controller service does not exist, and you trigger a try/catch block, which is expensive. In some cases, this may trigger abstract factories which map to a controller you do not expect, which could lead to unexpected consequences, including security violations.
- Finally, as noted: you now have "magic", and you can have situations where you're unsure what controller a URI will trigger, and how it will ensure that it can locate the service. If, instead, you have a literal segment in your route, and then specify a single controller default that resolves to a known service, you know that the correct controller will be selected every time. This is a large part of why ZF2 did not define a `/:controller/:action` route in the stack by default (though we did in the skeleton, albeit with a recommendation not to use it), and why the skeleton as of v3 does not define any such routes, even as commented optional configuration.
