### ISSUE TITLE
Disable config caching by default

### ISSUE THREAD

**Issue by olegkrivtsov** [zendframework/ZendSkeletonApplication#368]
I tried to install the latest version of Zend Skeleton Application. I installed session support, standard plugins and form support. Then I opened the skeleton in web browser (Chrome). Then I added the `aboutAction()` action to `IndexController` and a Literal route for that action and a view template. So far so good.

Then I tried to open the About page in my browser, I've received error "The URL couldn't be matched by routing". Confusing. After many trials and errors, I've realised that disabling the config caching in `application.config.php` fixes the problem.

So, I suggest that the config caching be disabled by default (currently it is enabled).

**Comment by samsonasik** [comment]
you can run:
```
$ composer development-enable
```

**Comment by olegkrivtsov** [comment]
I think that caching should be disabled BY DEFAULT. When you download Zend Skeleton App, you definitely plan to develop your website from it, so config caching enabled by default may be a problem. You don't identify this problem in your documentation, so novice users will be confused.

**Comment by samsonasik** [comment]
it is documented: http://zendframework.github.io/tutorials/getting-started/skeleton-application/#development-mode

**Comment by GeeH** [comment]
Ping @weierophinney 

I agree with this. I would like to see development mode enabled by default so that no caching happens, then a "deploying to production" document explaining what you need to do to make an app production ready. 

Possible solution is to just disable the caching in the `application.config.php` with the shipped application. A better solution would be to run  `composer development-enable` as part of the create project process.

**Comment by vrkansagara** [comment]
Agree with gray.

**Comment by adamlundrigan** [comment]
Adding this to the `scripts` section of the `composer.json` should be sufficient:

```
"post-create-project-cmd": "@development-enable",
```
